services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  back-dynamic-wp-1:
    depends_on:
      - db
    image: wordpress:6.0.1-php8.0-fpm-alpine
    container_name: back-dynamic-wp-1
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  back-dynamic-angie-1:
    depends_on:
      - back-dynamic-wp-1
    image: docker.angie.software/angie:latest
    container_name: back-dynamic-angie-1
    restart: unless-stopped
    volumes:
      - ./back-dynamic-angie-1.conf:/etc/angie/http.d/default.conf:ro
      - wordpress:/var/www/html
    networks:
      - app-network

  back-static-angie-1:
    image: docker.angie.software/angie:latest
    container_name: back-static-angie-1
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
      - ./back-static-angie.conf:/etc/angie/http.d/default.conf:ro
    networks:
      - app-network

  back-static-angie-2:
    image: docker.angie.software/angie:latest
    container_name: back-static-angie-2
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
      - ./back-static-angie.conf:/etc/angie/http.d/default.conf:ro
    networks:
      - app-network


  front-1:
    depends_on:
      - back-dynamic-angie-1
      - back-static-angie-1
    image: docker.angie.software/angie:latest
    container_name: front-1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./front-1.conf:/etc/angie/http.d/default.conf:ro
      - /var/acme-challenge/:/var/acme-challenge/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    networks:
      - app-network

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge
