proxy_cache_valid 1m;
proxy_cache_key $scheme$host$request_uri;
proxy_cache_path /var/angie_cache levels=1:2 keys_zone=one:10m:file=/etc/angie/cache.state inactive=48h
max_size=800m;

ssl_session_cache shared:SSL:1m;
ssl_session_timeout 24h;

ssl_session_tickets on; # включено по умолчанию, но пропишем явно

limit_req_zone $binary_remote_addr zone=lone:10m rate=1r/s;

error_log /var/log/angie/error.log warn;
access_log /var/log/angie/access.log;

upstream wordpress_static {
    server back-static-angie-1:80;
}

upstream wordpress_dynamic {
    server back-dynamic-angie-1:80;
}

server {
    listen 80;
    listen [::]:80;

    server_name otus-angie-14.s7h.ru;

    return 301 https://otus-angie-14.s7h.ru$request_uri;

}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic reuseport;

    http2 on;
    http2_max_concurrent_streams 128;
    http2_chunk_size 8k;

    http3 on;
    add_header Alt-Svc 'h3=":443"; ma=86400';

    server_name otus-angie-14.s7h.ru;

    ssl_certificate /etc/letsencrypt/live/otus-angie-14.s7h.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/otus-angie-14.s7h.ru/privkey.pem;

    add_header Strict-Transport-Security max-age=3600; # HSTS на час

    root /var/www/html;

    # известные статичные ресурсы направим на хосты статики
    location ~*\.(gif|ico|jpeg|jpg|png|pdf|css|js|svg)$
            /wp-includes/
            /wp-content/uploads/ {
        proxy_pass http://wordpress_static;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
    }

    # в админку будем пускать только из собственной сети
    location /wp-admin/ {
        allow 76.78.152.0/21;
        allow 192.168.129.1;
        deny all;

        proxy_pass http://wordpress_dynamic;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # запрос/выпуск сертификатов реализуем прямо на frontend
    location .well-known/acme-challenge/ {
        alias /var/acme-challenge/;
    }

    # всё остальное направляем на серверы с динамикой
    location / {
        proxy_pass http://wordpress_dynamic;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
    }

}
